In [ ]:
!pip install pymysql

In [7]:
import pymysql
import pandas as pd

# DB 연결 설정
conn = pymysql.connect(
    host='project-db-cgi.smhrd.com',
    port=3307,
    user='CGI_25IS_LI_P2_3',
    password='smhrd3',
    db='CGI_25IS_LI_P2_3',
    charset='utf8mb4'
)

In [9]:
# 쿼리 작성
query =query = """
                select r.*, m.mb_img
    			from t_review r
    			inner join t_member m on m.mb_id = r.mb_id
                """

# 쿼리 실행 후 데이터프레임으로 변환
df = pd.read_sql(query, conn)

C:\Users\smhrd\AppData\Local\Temp\ipykernel_17264\933017174.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [11]:
df

,review_idx,res_idx,mb_id,review_content,img_link,ratings,likes,created_at,mb_nick,mb_img
0,657,11010243,naver12345,새로운 지점으로 옮기고 첫 방문인데 매장이 넓어지고 신식으로 멋있어졌네요 ^__^ ...,None,0.0,0,2025-08-05 15:48:39,,https://res.cloudinary.com/duyrajdqg/image/upl...
1,658,11010243,naver12345,"광주 맛집으로 검색해서 온건데 김치가 너무너무 맛있었고, 재료가 하나같이 다 신선하...",None,0.0,0,2025-08-05 15:48:39,,https://res.cloudinary.com/duyrajdqg/image/upl...
2,659,11010243,naver12345,유튜브에 채널광주에서 보고 너무 맛있어버여서 방문했는데 정말 푸짐하고 신선하고! 리...,None,0.0,0,2025-08-05 15:48:39,,https://res.cloudinary.com/duyrajdqg/image/upl...
3,660,11010243,naver12345,어르신하고 같이 오기 전에 먼저 와봤는데 너무 좋네요.\r\n반찬 간도 너무 세지 ...,None,0.0,0,2025-08-05 15:48:39,,https://res.cloudinary.com/duyrajdqg/image/upl...
4,661,11010243,naver12345,진월동에 있을때 부터 제가 좋아하는 맛집이예요\r\n반찬 하나하나 정성스럽게 맛있고...,None,0.0,0,2025-08-05 15:48:39,,https://res.cloudinary.com/duyrajdqg/image/upl...
...,...,...,...,...,...,...,...,...,...,...
46401,47063,920150826,test3333,짱 마싯어서 맨날 가고 싶어요4,None,4.0,0,2025-08-06 18:11:02,김이담,https://res.cloudinary.com/duyrajdqg/image/upl...
46402,47064,920150826,test3333,!@##$@#@%#@%%#@$#$^@#^3,None,3.0,0,2025-08-06 18:11:14,김이담,https://res.cloudinary.com/duyrajdqg/image/upl...
46403,47065,19615882,popo6866,ㅁ,None,1.0,0,2025-08-06 19:39:36,카리나,https://res.cloudinary.com/duyrajdqg/image/upl...
46404,47066,19615882,popo6866,진짜쩔어,None,1.0,0,2025-08-06 19:40:36,카리나,https://res.cloudinary.com/duyrajdqg/image/upl...
46405,47067,8200402,popo6866,이집 참 괜찮아요,None,5.0,0,2025-08-07 09:18:18,카리나,https://res.cloudinary.com/duyrajdqg/image/upl...